[package]
name = "sqlite_test"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
rocket_codegen = "0.5.0"
diesel = { version = "2.1.0", features = ["sqlite"] }
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
